# MD013/line-length
MD013: false

# MD026/no-trailing-punctuation
no-trailing-punctuation:
  # Allowed: !
  punctuation: .,;:。，；：！

# MD033/no-inline-html
MD033: false

# MD040/fenced-code-language
MD040: false

# MD041/first-line-heading
MD041: false
