name: Quality-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Lint Check
        run: npm install && npm run lint

  check-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Style Check
        run: npm install && npm run check
