name: QA

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # only run this when markdown files are in the diff
      # - run: pnpm dlx markdownlint-cli **/*.md
      - run: pnpm install
      - run: pnpm check
