name: Quality-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Lint Check
        run: npm install && npm run lint

  check-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Style Check
        run: npm install && npm run check
